config/routes.rb
Networkingapp::Application.routes.draw do
  resources :memberships
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :after_signup
  
  resources :cities do resources :groups do 
      get 'join', 'unjoin', :on => :member 
    end
  end
    
  get "home/index"

  root 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships, :limit => 12
  belongs_to :city
  belongs_to :user
  attr_accessible :name, :city_id, :address, :venue, :time, :description, :time_specific, :rules, :user_id
  
  validates_presence_of :name, :address, :venue, :description, :time_specific
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :authenticate_user!, :except => [:index, :show]

  # GET /groups
  # GET /groups.json
  def index
    @city = City.find(city_group_path)
    @groups = @city.groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @user = current_user
  end

  # GET /groups/new
  def new
    @city = City.find(params[:city_id])
    @group = @city.groups.new
  end

  # GET /groups/1/edit
  def edit
    @city = City.find(params[:city_id])
    @group = @city.groups.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @city = City.find(params[:city_id])
    @group = @city.groups.new(params[:group])
    @group.user = current_user

    respond_to do |format|
      if @group.save
        gflash :success => "Group page was successfully created."
        format.html { redirect_to [@city, @group] }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: city_group_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    @city = City.find(params[:city_id])
    @group = @city.groups.find(params[:id])
    
    respond_to do |format|
        if @group.update_attributes(params[:group])
        gflash :notice => "Your group was successfully updated."
        format.html { redirect_to [@city, @group] }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: (@group).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @city = City.find(params[:city_id])
    @group = @city.groups.find(params[:id])
    @group.destroy
    respond_to do |format|
      gflash :notice => "Your group was successfully deleted."
      format.html { redirect_to root_url}
      format.json { head :no_content }
    end
  end
  
   def join
         @group = Group.find(params[:id])
         @membership = @group.memberships.build(:user_id => current_user.id)

         respond_to do |format|
           if @membership.save
             gflash :success => "You have joined this group!"
             format.html { redirect_to(city_group_path) }
             format.xml  { head :ok }
           else
             format.html { redirect_to(city_group_path, :notice => 'You have already joined a networking group.') }
             format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
           end
         end
       end

     def unjoin 
       @group = Group.find(params[:id])
       @membership = @group.memberships.find_by_user_id(current_user.id)
       @membership.destroy rescue nil
       gflash :success => "You have left this group!"
       redirect_to(city_group_path)
     end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params[:group]
    end
    
  
       
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for([@city, @group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
	<div class="row-fluid">
		<div class="span12">
			<center>
Give your group a cool name:<br>
<%= f.text_field :name, :placeholder => "Power Attorneys & CPAs" %><br>

Name of venue, if you don't have one yet just put TBD:<br>
<%= f.text_field :venue, :placeholder => "The W Hotel Lounge" %><br>

Address of venue, if you don't have one yet just put TBD:<br>
<%= f.text_field :address, :placeholder => "200 Rt. 110 Melville, NY" %><br>

This group will meet: <br>
<%= f.select :time, [['Daily', 'Daily'], ['Weekly', 'Weekly'], ['Bi-Weekly', 'Bi-weekly'], ['Monthly', 'Monthly']] %><br>

<b>Group Description:</b> In a few sentences explain what your group is all about.<br>
<%= f.text_area :description, :class=> "input-xxlarge", :placeholder => "This is a business networking group for attorneys practicing law in varying specialties." %> <br>

<b>Meeting Date/Time:</b> Provide more specifics on the date and time of your meetings. <br>
<%= f.text_area :time_specific, :class=> "input-xxlarge", :placeholder => "We meet every Thursday at 7 AM" %><br>

<b>Rules:</b> You can set any rules or expectations for your group (Optional).<br>
<%= f.text_area :rules, :class=> "input-xxlarge", :placeholder => "We allow a maximum of 3 absences per quarter" %>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>
</center>
		</div>
	</div>
</div>		

app/views/groups/edit.html.erb
<center><h1>Edit Group</h1></center>

<%= render 'form' %>

<%= link_to 'Show', city_group_path %> |
<%= link_to 'Back', city_group_path %>

app/views/groups/index.html.erb
<h1>Listing group_pages</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @city.groups.each do |group| %>

	<%= group.name %>
      <tr>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group page', new_group_path %>

app/views/groups/new.html.erb
<center><h1>Start a New Group</h1></center>

<%= render 'form' %>

app/views/groups/show.html.erb
<div class="row-fluid">
<div class="span12">
	<div id="group-show-background">
			<div class="row-fluid">		
				<div class="span4">
					<div class="member-count-border">
					<div class="member-count">
						<%= @group.memberships.count %><br>
					</div>
					<div class="member-word-members"><br>
					members
					</div>
					</div>
				</div>
		
		<div class="span8">
			<div class="group-name-title">
				<%= @group.name %>
			</div>
		</div>
		</div>
			<div class="row-fluid">
			<div class="span3">
				</div>
				<div class="span9">
				<div class="group-show-subheading">
				Meets <%= @group.time.downcase %> at <%= @group.venue %> <%= @group.address %>
				</div>
				</div>
			</div>
			</div>
		
	</div>
</div>
</div>

</div>	

<% if user_signed_in? %>

<%#- This is Semantic UI, used to add a dynamic sidebar -%>

        <div class="ui thin vertical inverted labeled icon left overlay sidebar menu">	
        </div>
        <div class="ui black huge launch right attached button">
	        <span class="text" style="display:none;"></span>
	        <i class="icon list layout"></i>
        </div>

<div class="ui sidebar"> 
	<div class="row-fluid">
		<div class="span12">
		
			
			
			<%  if @group.memberships.count < 13 && unless @group.users.where(:email => "#{current_user.email}").exists? %>
				<%= link_to join_city_group_path(@group.city.id,@group), :class => "new-city-group-button", :confirm => "Are you sure you want to join this group?" do %> 
			<div class="positive ui button">Join Group</div>
			<% end %>	
			<% end %>
		
			<% else %>
			
			
			<%= link_to unjoin_city_group_path(@group.city.id,@group), :class => "new-city-group-button",  :confirm => "Are you sure you want to leave this group?" do %> 
				<div class="negative ui button">Leave Group</div>
			<% end %>
			<% end %>
		
			
			 <% if current_user.groups.exists? %>
			<div class="ui piled segment">
			  <center><h4>My Group</h4></center>
			 <% current_user.groups.each do |user_group| %>
				<center><%= link_to user_group.name, city_group_path(user_group.city_id,user_group.id) %></center>
				<% end %>
			</div>
			<% end %>
			
			<% if current_user.memberships.exists? %>
			<div class="ui piled segment">
			  <center><h4>Joined Group</h4></center>
			  <% current_user.memberships.each  do |membership| %>
			  <center><%= link_to membership.group.name, city_group_path(membership.group.city.id,membership.group.id) %></center>
			  <% end %>
			</div>
			<% end %>
			
	
		</div>
	</div>
</div>


<% else %>

<div class="ui sidebar"> 
	<div class="row-fluid">
		<div class="span12">
		Sorry, please login to see this menu!
		</div>
	</div>
</div>

<% end %>


<script>
$(".launch.button").mouseenter(function(){
		$(this).stop().animate({width: '70px'}, 300, 
             function(){$(this).find('.text').show();});
	}).mouseleave(function (event){
		$(this).find('.text').hide();
		$(this).stop().animate({width: '70px'}, 300);
	});
$(".ui.sidebar").sidebar({overlay: false})
                .sidebar('attach events','.ui.launch.button');
</script>



<div class="container">

		
	
<% if user_signed_in? %>
<% if @group.users.where(:email => "#{current_user.email}").exists? %>

<div class="row-fluid">


<div class="span2">
	<% @group.memberships.each do |members| %><br>
	<%= gravatar_tag members.user.email, :size => 80 %><br>
	<% end %>
</div>

<div class="span6">
	<% @group.memberships.each do |members| %><br>
	<div class="group-member-name">
	<%= members.user.first_name %> <%= members.user.last_name %> 
	</div>
	<%= members.user.industry %> <i><%= members.user.focus_area %></i><br>
	<%= link_to "Contact" " " "#{members.user.first_name}", "mailto:#{members.user.email}" %>
	<% if user_signed_in? && @group.user == current_user %>
	<%= link_to "Remove User", membership_path(members), :method => :delete %><br>
	<% end %>
	<% end %>
	

</div>

<div class="span4"><br><br>
	<b>Description</b><br>
	<%= simple_format @group.description %><br>
	<b>Time & Date</b><br>
	<%= simple_format @group.time_specific %><br>
	<b>Rules</b><br>
	<%= simple_format @group.rules %>
</div>
		
</div>



<% end %>
<% end %>

<% if user_signed_in? %>
<% unless @group.users.where(:email => "#{current_user.email}").exists? %>
		<div class="row-fluid"><br><br>
		<center><h2>You must be a group member to see group details.</h></center><br>
			</div>
				<div class="row-fluid">
				<div class="span8">
				<% @group.memberships.each do |members| %>
				<b>Industries Represented:</b><br>
				<%= members.user.industry %>  <i><%= members.user.focus_area %></i><br>
				<% end %>
				</div>
				
				<div class="span4">
					<b>Description</b><br>
					<%= simple_format @group.description %><br>
					<b>Time & Date</b><br>
					<%= simple_format @group.time_specific %><br>
					<b>Rules</b><br>
					<%= simple_format @group.rules %>
				</div>
	</div>
<% end %>
<% end %>

<% if user_signed_in? && @group.user == current_user %>
<%= link_to "Edit Group", edit_city_group_path %><br>
<%= link_to "Delete Group", city_group_path, :confirm => "are you sure?", :method => :delete %>
<% end %>