config/routes.rb
Networkingapp::Application.routes.draw do
  resources :memberships
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :after_signup
  
  resources :cities do resources :groups do 
      get 'join', 'unjoin', :on => :member 
    end
  end
    
  get "home/index"

  root 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :groups
  attr_accessible :name, :user_id
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
before_action :authenticate_user!, :except => [:index, :show]

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
    @groups_grid = initialize_grid(Group)
  end

  # GET /groups/new
  def new
    @city = City.new
  end

  def edit
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @city }
      else
        format.html { render action: 'new' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end
  
    
end

app/views/cities/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.text_field :name %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/cities/index.html.erb
<h1>Networking Groups</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>




  <tbody>
    <% @cities.each do |city| %>
		
      <tr>
		<td><%= city.name %></td>
		<td>(<%= city.memberships.count %>/12)</td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_city_path %>

app/views/cities/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/cities/show.html.erb
<div class="row-fluid">
	<div class="span12">
		<div id="group-show-title">	
			<%= @city.name %> 
		</div>	
	</div>
</div>

<% if user_signed_in? %>

<%#- This is Semantic UI, used to add a dynamic sidebar -%>

      <div class="ui thin vertical inverted labeled icon left overlay sidebar menu">	
      </div>
        <div class="ui black huge launch right attached button">
	        <span class="text" style="display:none;"></span>
	        <i class="icon list layout"></i>
        </div>

<div class="ui sidebar"> 
		<div class="row-fluid">
			<div class="span12">
				
				
<script>
$(".launch.button").mouseenter(function(){
		$(this).stop().animate({width: '70px'}, 300, 
             function(){$(this).find('.text').show();});
	}).mouseleave(function (event){
		$(this).find('.text').hide();
		$(this).stop().animate({width: '70px'}, 300);
	});
$(".ui.sidebar").sidebar({overlay: false})
                .sidebar('attach events','.ui.launch.button');
</script>


<% unless current_user.memberships.exists? %>				
<%= link_to new_city_group_path(@city), :class =>"new-city-group-button" do %>
<div class="positive ui button">Start a Group</div>	
</div>
<% end %>
<% end %>

 <% if current_user.groups.exists? %>
	<div class="ui piled segment">
	  <center><h4>My Group</h4></center>
	 <% current_user.groups.each do |user_group| %>
		<center><%= link_to user_group.name, city_group_path(user_group.city_id,user_group.id) %></center>
		<% end %>
	</div>
		<% end %>
		
<% if current_user.memberships.exists? %>
<div class="ui piled segment">
  <center><h4>Joined Group</h4></center>
  <% current_user.memberships.each  do |membership| %>
  <center><%= link_to membership.group.name, city_group_path(membership.group.city.id,membership.group.id) %></center>
  <% end %>
</div>
	<% end %>

		    </div>
	    </div>
</div>

<% end %>

<div class="container">

<div class="row-fluid">
		
	<div class="row-fluid">
	<div class="span3">
	<b>NAME</b>
	<br>
	<hr>

	<% @city.groups.each do |group| %>
	<%= link_to group.name, city_group_path(@city, group.id) %><br><br>
	<% end %>
	</div>


	<div class="span3">
	<b>MEMBERS</b><br><hr>
	<% @city.groups.each do |group| %>
	<%= group.memberships.count %>/12<br><br>
	<% end %>
	</div>


	<div class="span3">
	<b>FREQUENCY</b><br><hr>
	<% @city.groups.each do |group| %>
	<%= group.time %><br><br>
	<% end %>
	</div>

	<div class="span3">
	<b>DESCRIPTION</b><br><hr>
	<% @city.groups.each do |group| %>
	<%= group.description %><br><br>
	<% end %>

</div>